INSERT INTO teams (id, abbr, name, division, league, ballpark_id) VALUES
    (108, 'LAA', 'Los Angeles Angels', 'AL West', 'AL', NULL),
    (109, 'ARI', 'Arizona Diamondbacks', 'NL West', 'NL', NULL),
    (110, 'BAL', 'Baltimore Orioles', 'AL East', 'AL', NULL),
    (111, 'BOS', 'Boston Red Sox', 'AL East', 'AL', NULL),
    (112, 'CHC', 'Chicago Cubs', 'NL Central', 'NL', NULL),
    (113, 'CIN', 'Cincinnati Reds', 'NL Central', 'NL', NULL),
    (114, 'CLE', 'Cleveland Guardians', 'AL Central', 'AL', NULL),
    (115, 'COL', 'Colorado Rockies', 'NL West', 'NL', NULL),
    (116, 'DET', 'Detroit Tigers', 'AL Central', 'AL', NULL),
    (117, 'HOU', 'Houston Astros', 'AL West', 'AL', NULL),
    (118, 'KCR', 'Kansas City Royals', 'AL Central', 'AL', NULL),
    (119, 'LAD', 'Los Angeles Dodgers', 'NL West', 'NL', NULL),
    (120, 'WSH', 'Washington Nationals', 'NL East', 'NL', NULL),
    (121, 'NYM', 'New York Mets', 'NL East', 'NL', NULL),
    (133, 'ATH', 'Athletics', 'AL West', 'AL', NULL),
    (134, 'PIT', 'Pittsburgh Pirates', 'NL Central', 'NL', NULL),
    (135, 'SDP', 'San Diego Padres', 'NL West', 'NL', NULL),
    (136, 'SEA', 'Seattle Mariners', 'AL West', 'AL', NULL),
    (137, 'SFG', 'San Francisco Giants', 'NL West', 'NL', NULL),
    (138, 'STL', 'St. Louis Cardinals', 'NL Central', 'NL', NULL),
    (139, 'TBR', 'Tampa Bay Rays', 'AL East', 'AL', NULL),
    (140, 'TEX', 'Texas Rangers', 'AL West', 'AL', NULL),
    (141, 'TOR', 'Toronto Blue Jays', 'AL East', 'AL', NULL),
    (142, 'MIN', 'Minnesota Twins', 'AL Central', 'AL', NULL),
    (143, 'PHI', 'Philadelphia Phillies', 'NL East', 'NL', NULL),
    (144, 'ATL', 'Atlanta Braves', 'NL East', 'NL', NULL),
    (145, 'CHW', 'Chicago White Sox', 'AL Central', 'AL', NULL),
    (146, 'MIA', 'Miami Marlins', 'NL East', 'NL', NULL),
    (147, 'NYY', 'New York Yankees', 'AL East', 'AL', NULL),
    (158, 'MIL', 'Milwaukee Brewers', 'NL Central', 'NL', NULL)
ON CONFLICT (id) DO UPDATE
SET
    abbr = EXCLUDED.abbr,
    name = EXCLUDED.name,
    division = EXCLUDED.division,
    league = EXCLUDED.league,
    ballpark_id = EXCLUDED.ballpark_id;
